import type { Transaction } from "@/lib/finance-types";

export const seedTransactions: Transaction[] = [
  {
    id: "txn-001",
    date: "2026-01-02",
    description: "Monthly salary",
    amount: 6200,
    category: "Salary",
    type: "income",
  },
  {
    id: "txn-002",
    date: "2026-01-04",
    description: "Apartment rent",
    amount: 1850,
    category: "Housing",
    type: "expense",
  },
  {
    id: "txn-003",
    date: "2026-01-11",
    description: "Neighborhood market",
    amount: 286,
    category: "Food",
    type: "expense",
  },
  {
    id: "txn-004",
    date: "2026-01-17",
    description: "Freelance brand sprint",
    amount: 960,
    category: "Consulting",
    type: "income",
  },
  {
    id: "txn-005",
    date: "2026-01-22",
    description: "City transit pass",
    amount: 112,
    category: "Transport",
    type: "expense",
  },
  {
    id: "txn-006",
    date: "2026-02-02",
    description: "Monthly salary",
    amount: 6200,
    category: "Salary",
    type: "income",
  },
  {
    id: "txn-007",
    date: "2026-02-04",
    description: "Apartment rent",
    amount: 1850,
    category: "Housing",
    type: "expense",
  },
  {
    id: "txn-008",
    date: "2026-02-09",
    description: "Power and water bill",
    amount: 214,
    category: "Utilities",
    type: "expense",
  },
  {
    id: "txn-009",
    date: "2026-02-14",
    description: "Dining and coffee",
    amount: 342,
    category: "Food",
    type: "expense",
  },
  {
    id: "txn-010",
    date: "2026-02-27",
    description: "Tax refund",
    amount: 740,
    category: "Refunds",
    type: "income",
  },
  {
    id: "txn-011",
    date: "2026-03-02",
    description: "Monthly salary",
    amount: 6200,
    category: "Salary",
    type: "income",
  },
  {
    id: "txn-012",
    date: "2026-03-04",
    description: "Apartment rent",
    amount: 1850,
    category: "Housing",
    type: "expense",
  },
  {
    id: "txn-013",
    date: "2026-03-12",
    description: "Groceries and pantry",
    amount: 398,
    category: "Food",
    type: "expense",
  },
  {
    id: "txn-014",
    date: "2026-03-18",
    description: "Dental checkup",
    amount: 260,
    category: "Health",
    type: "expense",
  },
  {
    id: "txn-015",
    date: "2026-03-24",
    description: "Team offsite flight",
    amount: 620,
    category: "Travel",
    type: "expense",
  },
  {
    id: "txn-016",
    date: "2026-04-02",
    description: "Monthly salary",
    amount: 6200,
    category: "Salary",
    type: "income",
  },
  {
    id: "txn-017",
    date: "2026-04-04",
    description: "Apartment rent",
    amount: 1850,
    category: "Housing",
    type: "expense",
  },
  {
    id: "txn-018",
    date: "2026-04-08",
    description: "Farmers market haul",
    amount: 520,
    category: "Food",
    type: "expense",
  },
  {
    id: "txn-019",
    date: "2026-04-15",
    description: "Streaming and cinema",
    amount: 168,
    category: "Entertainment",
    type: "expense",
  },
  {
    id: "txn-020",
    date: "2026-04-21",
    description: "Client strategy workshop",
    amount: 1280,
    category: "Consulting",
    type: "income",
  },
  {
    id: "txn-021",
    date: "2026-04-25",
    description: "Ride share and fuel",
    amount: 196,
    category: "Transport",
    type: "expense",
  },
];
